### ISSUE TITLE
Building a Stream

### ISSUE THREAD

**Issue by EndallBatan93** [logbee/keyscore#3]
Currently a stream cannot be built. 
Because in the FilterManager the methods:

getSinkStageLogicConstructor,
getSourceStageLogicConstructor,
getFilterStageLogicConstructor

do fail because the logicClass.getConstructor(...) fail with a NoSuchMethodException

logicClass.getConstructors() returns an empty array.

**Comment by Avoliq** [comment]
Changed the logicClass.getContructor(...) to logicClass.getConstructors()(0) to find the correct constructor but it is still not possible to instantiate a stage object due to a ArgumentMissMatchException. 

But the found constructor's parameterTypes are as expected except the Shape missing the Dataset Type.

Using Scala reflection instead of the java librarys might be a solution

**Comment by kKdH** [comment]
Hey Folks,
thanks @EndallBatan93 for raising this issue and thanks @Avoliq for clarification.
I found the problem in the `FilterManager`. The method `loadStageLogicClass` loads the StageLogic class but to do this, it creates a new `ClassLoader`. That leads to the  ArgumentMissMatchException later, because two classes (the parameter types of the constructor) are only equal if both where loaded with the **same** `ClassLoader`.

For a first fix i replaced:
```scala
ScalaClassLoader(getClass.getClassLoader).tryToLoadClass(className)
```

with:
```scala
Option(getClass.getClassLoader.loadClass(className))
```

Kind regards,
Elmar

**Comment by kKdH** [comment]
Pleas let me know if the problem still exists.
